import { PathOptions } from 'leaflet';
export declare const TRANSPARENT_PIXEL: string;
export declare const ANIMATION_DELAY: number;
export declare const EXAMPLE_CONTENT: string;
export declare const OSM_TILE_LAYER_URL: string;
export declare const IMAGE_OVERLAY_URL: string;
export declare const EXAMPLE_WMS_LAYER_URL: string;
export declare const EXAMPLE_WMS_LAYER_NAMES: string[];
export declare const ATTRIBUTION_PREFIX: string;
export declare const DEFAULT_STYLE: PathOptions;
