import { EventEmitter, OnDestroy } from '@angular/core';
import { ImageOverlay, LatLngBounds, LatLngBoundsExpression, LeafletEvent, LeafletMouseEvent, PopupEvent, TooltipEvent } from 'leaflet';
import { LayerGroupProvider } from './layer-group.provider';
import { LayerProvider } from './layer.provider';
export declare class ImageOverlayDirective extends ImageOverlay implements OnDestroy {
    urlChange: EventEmitter<string>;
    displayChange: EventEmitter<boolean>;
    opacityChange: EventEmitter<number>;
    boundsChange: EventEmitter<LatLngBounds>;
    northChange: EventEmitter<number>;
    eastChange: EventEmitter<number>;
    southChange: EventEmitter<number>;
    westChange: EventEmitter<number>;
    addEvent: EventEmitter<LeafletEvent>;
    removeEvent: EventEmitter<LeafletEvent>;
    popupopenEvent: EventEmitter<PopupEvent>;
    popupcloseEvent: EventEmitter<PopupEvent>;
    tooltipopenEvent: EventEmitter<TooltipEvent>;
    tooltipcloseEvent: EventEmitter<TooltipEvent>;
    clickEvent: EventEmitter<LeafletMouseEvent>;
    dbclickEvent: EventEmitter<LeafletMouseEvent>;
    mousedownEvent: EventEmitter<LeafletMouseEvent>;
    mouseoverEvent: EventEmitter<LeafletMouseEvent>;
    mouseoutEvent: EventEmitter<LeafletMouseEvent>;
    contextmenuEvent: EventEmitter<LeafletMouseEvent>;
    constructor(layerGroupProvider: LayerGroupProvider, layerProvider: LayerProvider);
    ngOnDestroy(): void;
    setUrl(url: string): this;
    url: string;
    setOpacity(val: number): this;
    opacity: number;
    display: boolean;
    setBounds(val: LatLngBoundsExpression): this;
    bounds: LatLngBounds;
    north: number;
    east: number;
    south: number;
    west: number;
    crossOrigin: boolean;
    alt: string;
    interactive: boolean;
    attribution: string;
}
