import { AfterContentInit, EventEmitter, OnDestroy } from '@angular/core';
import { Feature as GeoJSONFeature } from 'geojson';
import { FillRule, LatLng, LatLngBounds, LatLngBoundsLiteral, LatLngExpression, LatLngTuple, LeafletMouseEvent, LineCapShape, LineJoinShape, PathOptions, PolylineOptions, PopupEvent, Rectangle, TooltipEvent } from 'leaflet';
import { LayerGroupProvider } from './layer-group.provider';
export declare class RectangleDirective<T> extends Rectangle implements OnDestroy, AfterContentInit {
    displayChange: EventEmitter<boolean>;
    strokeChange: EventEmitter<boolean>;
    colorChange: EventEmitter<string>;
    weightChange: EventEmitter<number>;
    opacityChange: EventEmitter<number>;
    lineCapChange: EventEmitter<string>;
    lineJoinChange: EventEmitter<string>;
    dashArrayChange: EventEmitter<string>;
    dashOffsetChange: EventEmitter<string>;
    fillChange: EventEmitter<boolean>;
    fillColorChange: EventEmitter<string>;
    fillOpacityChange: EventEmitter<number>;
    fillRuleChange: EventEmitter<string>;
    classNameChange: EventEmitter<string>;
    styleChange: EventEmitter<PathOptions>;
    latLngsChange: EventEmitter<LatLng[]>;
    boundsChange: EventEmitter<LatLngBounds>;
    northChange: EventEmitter<number>;
    eastChange: EventEmitter<number>;
    southChange: EventEmitter<number>;
    westChange: EventEmitter<number>;
    geoJSONChange: EventEmitter<GeoJSONFeature<GeoJSON.Polygon | GeoJSON.MultiPolygon, T>>;
    addEvent: EventEmitter<Event>;
    removeEvent: EventEmitter<Event>;
    popupopenEvent: EventEmitter<PopupEvent>;
    popupcloseEvent: EventEmitter<PopupEvent>;
    tooltipopenEvent: EventEmitter<TooltipEvent>;
    tooltipcloseEvent: EventEmitter<TooltipEvent>;
    clickEvent: EventEmitter<LeafletMouseEvent>;
    dbclickEvent: EventEmitter<LeafletMouseEvent>;
    mousedownEvent: EventEmitter<LeafletMouseEvent>;
    mouseoverEvent: EventEmitter<LeafletMouseEvent>;
    mouseoutEvent: EventEmitter<LeafletMouseEvent>;
    contextmenuEvent: EventEmitter<LeafletMouseEvent>;
    private initialized;
    constructor(layerGroupProvider: LayerGroupProvider);
    ngAfterContentInit(): void;
    ngOnDestroy(): void;
    setBounds(val: LatLngBounds | LatLngBoundsLiteral): this;
    bounds: LatLngBounds;
    north: number;
    east: number;
    south: number;
    west: number;
    setLatLngs(val: (Array<(LatLng | LatLngTuple | LatLngExpression)> | Array<Array<(LatLng | LatLngTuple | LatLngExpression)>> | Array<Array<Array<(LatLng | LatLngTuple | LatLngExpression)>>>)): this;
    addLatLng(val: (LatLng | LatLngTuple | LatLngExpression) | Array<(LatLng | LatLngTuple | LatLngExpression)>): this;
    latLngs: LatLng[] | LatLng[][] | LatLng[][][];
    geoJSON: GeoJSONFeature<GeoJSON.Polygon | GeoJSON.MultiPolygon, T>;
    setStyle(style: PathOptions): this;
    opacity: number;
    stroke: boolean;
    color: string;
    weight: number;
    lineCap: LineCapShape;
    lineJoin: LineJoinShape;
    dashArray: string;
    dashOffset: string;
    fill: boolean;
    fillColor: string;
    fillOpacity: number;
    fillRule: FillRule;
    className: string;
    style: PolylineOptions;
    display: boolean;
    interactive: boolean;
    smoothFactor: number;
    noClip: boolean;
    properties: T;
}
